### ISSUE TITLE
server side code (php) si client side code (html)

### ISSUE THREAD

**Issue by danielnutu** [XDead27/UPtownEcothon-site#2]
recomand sa tii separat codul php de cel html. mai intai iti iei datele din db, le prelucrezi etc. mai jos in html afisezi doar. e mai curat asa. nu-i un 'must have'.
bucata de code de mai jos ai putea s-o spargi in 2:
* partea de CRUD sus in pagina (fisierul php)
* partea de afisare pe pozitie 
`
                        foreach($stmt as $row){
                            echo "<option value=" . $row['id'] . ">" . $row['name'] . "</option>";
                        }
`

https://github.com/XDead27/UPtownEcothon-site/blob/9401bff286132f20452a855b4325814763a61fd9/registration.php#L200-L220

**Comment by XDead27** [comment]
L-am trecut sus in pagina si am lasat doar un echo cu optiunile in client side
