### ISSUE TITLE
locatie gresita pentru tag-ul script

### ISSUE THREAD

**Issue by danielnutu** [XDead27/UPtownEcothon-site#4]
Scripts can be placed in the `<body>`, or in the `<head>` section of an HTML page, or in both.

direfenta este ca:
- in head se executa inainte
- se executa dupa ce a fost pagina incarcata

https://github.com/XDead27/UPtownEcothon-site/blob/9401bff286132f20452a855b4325814763a61fd9/registration.php#L277

**Comment by XDead27** [comment]
Mutat. Thanks
