### ISSUE TITLE
meniul intr-un fisier separat

### ISSUE THREAD

**Issue by danielnutu** [XDead27/UPtownEcothon-site#5]
meniul, footer-ul sau alte sectiuni ale site-ului le poti pune in fisiere separate (componente):
* header.php - deschizi html, css si js in tag-ul `<head>`, tag-ul `<body>`, logo, search etc
* menu.php - meniul
* footer.php - copyright and stuff, inchizi `</body>` si `</html>`

si referentiale in fisierele .php in locurile lor, ex:
in registration.php

```
<?php include('header.php');?>
<?php include('menu.php');?>

<?php 

   //continut php si html specific paginii 

?>

<?php include('footer.php');?>
```

https://github.com/XDead27/UPtownEcothon-site/blob/9401bff286132f20452a855b4325814763a61fd9/registration.php#L5

**Comment by XDead27** [comment]
Am adaugat meniul cu include acum.
