### ISSUE TITLE
mutat in header.php

### ISSUE THREAD

**Issue by danielnutu** [XDead27/UPtownEcothon-site#6]
dupa ce rezolvi issue-ul #5 poti pune acolo 

`<?php include_once 'config/dbconfig.php'; ?>`

nu mai stiu care este diferenta intre `include_once` si `require_once`

https://github.com/XDead27/UPtownEcothon-site/blob/9401bff286132f20452a855b4325814763a61fd9/registration.php#L8

**Comment by XDead27** [comment]
L-as lasa separat pentru ca meniul apare pe toate paginile, dar conexiunea la DB o folosesc doar in login / logout si register

**Comment by danielnutu** [comment]
corect, dar ca un best practice ai putea sa ai acel "include" intr-un fisier separat, incarcat intotdeauna.
acum ai login si register unde folosesti baza de date. poate peste 1-2 saptamani decizi sa afisezi pe prima pagina un top de echipe, de exemplu.
daca incluzi libraria in header nu inseamna ca o si instanteaza, deci nu consuma resurse/memorie.
